name: Push Docker Image to ECR and Deploy

on:
  push:
    branches:
      - production

jobs:
  push-to-ecr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Build and push Docker image to ECR
        run: |
          docker build -t sales10x-fe .
          docker_build_status=$?
          if [ $docker_build_status -ne 0 ]; then
            echo "Docker build failed, exiting..."
            exit $docker_build_status
          fi
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 302220238753.dkr.ecr.us-east-1.amazonaws.com
          docker tag sales10x-fe:latest 302220238753.dkr.ecr.us-east-1.amazonaws.com/sales10x-fe:latest
          docker push 302220238753.dkr.ecr.us-east-1.amazonaws.com/sales10x-fe:latest

      - name: SSH into Server and Run Script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            cd /home/ubuntu/deploy.sh
            sh deploy.sh